// 道場鬥技盃專用：每一戰開始前，出場角色各選一張主選與次選。
// 這個資料只描述卡牌與效果鍵；實際效果由 NinjaGame 的 tournament talent hooks 執行。
const TOURNAMENT_TALENTS = {
  fujin: { primary: [['wind_veil', '留風', '疾風閃開啟後隱形 1 秒。'], ['wind_borrow', '借風', '旋風斬二段拉回後，暈眩敵人 2 秒。']], secondary: [['light_step', '輕足', '任一主動技能結束後，移速 +8%，持續 0.8 秒；只刷新時間。'], ['wind_unload', '卸勁', '疾風閃結束後 0.6 秒內，跑速變為 35。']] },
  katon: { primary: [['scorched_dash', '焦土衝刺', '爆炎衝刺留下 150px 火痕 1.5 秒；命中火痕者受 2 傷害、緩速 40% 0.8 秒。'], ['spreading_fireball', '擴燃火球', '火球術命中時也施加烈焰印記。']], secondary: [['long_burning_mark', '長燃印記', '烈焰印記持續時間由 6 秒改為 7 秒。'], ['backfire_step', '反焰步', '火球成功命中時，向反方向滑退 135px。']] },
  forgefire: { primary: [['furnace_spin', '爐心旋斬', '烈火旋斬範圍由 130px 提高至 190px。'], ['wide_blade_path', '寬刃焚道', '炎神巨刃燃燒路徑長度改為 500px，持續 5 秒。']], secondary: [['spark_step', '火星踏步', '第三下普攻命中後移速 +10%，持續 0.75 秒。'], ['heavy_blade_anchor', '重刃定身', '炎神巨刃蓄力期間，受到的擊退距離 -60%。']] },
  suijin: { primary: [['surging_shield', '湧潮水幕', '水幕盾移速加成改為 35%，儲存傷害回復改為 90%。'], ['returning_tide', '回流水幕', '水龍彈造成傷害時，自身永久 +3 跑速，可無限疊加。']], secondary: [['wetland', '濕地', '水龍彈命中處留下 90px 水灘 1 秒；敵人踏入緩速 40%。'], ['clarity', '澄明', '水幕盾回復若少於 10 HP，下次冷卻改為 6 秒。']] },
  raijin: { primary: [['residual_charge', '殘電突破', '雷電拳冷卻改為 7 秒。'], ['chasing_thunder', '追雷拳', '雷電拳施放時先朝敵人瞬移 50px，再出拳。']], secondary: [['charged_pursuit', '帶電追擊', '閃電步後 1 秒內，下次普攻距離 +30px。'], ['thunder_stride', '雷行', '雷電拳完整兩段命中後，移速 +8%，持續 0.8 秒。']] },
  doton: { primary: [['shattered_bulwark', '碎岩壁壘', '岩壁護體結束時，在身後留下 80px 岩壁 1 秒，可擋一發投射物。'], ['spreading_quake', '擴散地裂', '地裂震外圈改為 230px；外圈造成 5 傷害，控制時間不變。']], secondary: [['rooted', '沉根', '所有受到的控制時間 -20%。'], ['rubble_aftershock', '碎石餘震', '地裂震後中心 100px 留下碎石 1.2 秒；敵人其中移速 -20%。']] },
  kage: { primary: [['surrounding_shadows', '包圍影陣', '影分身數量 +1。'], ['hunting_shadow_array', '追獵影陣', '黑刃突襲距離改為 400px，影子持續 5 秒。']], secondary: [['silent_afterimage', '無聲殘影', '黑刃突襲後留下 0.7 秒純視覺殘影。'], ['shadow_step', '影步', '黑刃突襲命中後移速 +10%，持續 0.7 秒。']] },
  rei: { primary: [['requiem_talisman', '鎮魂符', '靈爆符擊退由 40px 提高至 70px。'], ['guardian_talisman', '護佑符', '靈爆符命中自癒提高至 6 HP。']], secondary: [['spirit_pressure', '靈壓', '靈天審判蓄力速度 +10%。'], ['afterglow', '餘光', '靈天審判後留下 100px 光圈 3 秒；站在其中減傷 1。']] },
  dokusei: { primary: [['crippling_darts', '致殘毒鏢', '一次射出兩枚毒鏢，冷卻改為 5 秒。'], ['overgrown_thorns', '蔓生荊棘', '荊棘陷阱半徑提高至 130px。']], secondary: [['poison_stride', '毒行', '第四層毒爆後額外移速 +8%，持續 1 秒。'], ['lingering_mist', '毒霧殘留', '陷阱消失後留下 80px 毒霧 1 秒；敵人緩速 10%。']] },
  taijutsu: { primary: [['wall_breaker', '破壁投', '指令投撞牆判定容許值 +30px。'], ['pursuit_execution', '追身連環', '名門連環殺斬殺線改為 20%。']], secondary: [['extended_armor', '延續霸體', '技能後霸體提高至 2 秒。'], ['landing_pursuit', '落地追擊', '指令投結束後自動向落點前進 30px。']] },
  ranger: { primary: [['hunter_quiver', '獵行箭袋', '最大彈藥提高至 10，完整裝填改為 1.6 秒。'], ['spirit_leaf_reload', '靈葉快裝', '每 600ms 自動回復 1 發彈藥。']], secondary: [['wind_arrow', '風箭', '自然律動持續由 1.5 秒提升至 2 秒。'], ['quiet_leaf', '靜葉', '脫隱位移距離改為 400px。']] },
  warlock: { primary: [['crimson_chain', '猩紅長鏈', '鮮血枷鎖不扣自身血量，冷卻改為 10 秒。'], ['coagulated_bind', '凝血束縛', '鮮血枷鎖牽線中的敵人移速 -20%。']], secondary: [['low_health_dash', '殘血疾行', '血之護盾存在時移速加成由 5% 提高至 10%。'], ['infinite_blood_curse', '無限血咒', '血盾上限由 15 提高至 20。']] },
  ronin: { primary: [['falling_petals', '瓔落', '普攻命中時朝敵方位移 100px。'], ['deep_iai', '深居合', '居合・一閃命中後擊飛敵人 100px。']], secondary: [['zanshin', '殘心', '居合結束後 0.5 秒，受到的擊退距離 -35%。'], ['follow_cut', '追切', '瞬影斬緩速持續由 1 秒提高至 1.2 秒。']] },
  beastmaster: { primary: [['hunting_tentacle', '獵捕觸手', '深淵觸手距離提高至 340px，傷害 +2。'], ['thick_hide', '厚皮巨獸', '巨獸護盾由 20 提高至 30。']], secondary: [['beast_roar', '獸吼餘威', '巨獸定身結束後，敵人緩速 15% 0.8 秒。'], ['feral_remnant', '野性殘留', '巨獸型態結束後 0.8 秒內減傷 10%。']] },
  scorpion: { primary: [['skirmish_puppets', '散兵傀儡', '叛軍數量 +1。'], ['long_sentence', '加長刑期', '痛苦枷鎖冷卻改為 15 秒。']], secondary: [['spreading_thorns', '擴散毒棘', '第四下普攻毒棘荊地半徑由 80px 提高至 100px。'], ['threaded_no_step', '牽絲禁步', '痛苦枷鎖命中後，自動在敵人腳下生成毒荊棘地。']] },
  adjudicator: { primary: [['broad_verdict', '廣域判決', '最終判決半徑提高至 300px，持續 7 秒。'], ['severe_rebuttal', '嚴厲駁回', '異議駁回招架時仍可移動及攻擊。']], secondary: [['conviction', '定罪', '招架反擊沉默提高至 1.8 秒。'], ['justice_is_not_late', '正義不遲', '招架成功後跑速變為 40，持續 1 秒。']] },
  exileblade: { primary: [['rending_pursuit', '裂空追擊', '裂空突距離提高至 210px；結束後隱形 0.6 秒。'], ['hundredfold_focus', '百裂收束', '狂風百裂終結擊退提高至 190px，增加一段傷害。']], secondary: [['headwind', '逆風', '裂空突結束後移速 +20%，持續 0.7 秒。'], ['wind_blade_echo', '風刃殘響', '狂風百裂飛鏢命中處留下 60px 風圈 0.8 秒，緩速 20%。']] },
  puppeteer: { primary: [['guardian_puppet', '近衛傀儡', '傀儡繫繩距離改為 35px，傀儡傷害改為 4。'], ['hunter_puppet', '獵殺傀儡', '傀儡從敵方位置召喚；超距離時自動跑回可牽繩範圍。']], secondary: [['tight_line', '緊線警示', '傀儡・召喚/收回冷卻改為 3 秒。'], ['frayed_thread', '殘絲陷足', '收回傀儡時留下 70px 絲線圈 0.8 秒，緩速 12%。']] },
  azure_disciple: { primary: [['high_voltage_charge', '高壓蓄電', '移動累積電壓速度 +25%。'], ['combat_charging', '戰鬥充電', '普攻命中累積電壓由 20 提高至 40。']], secondary: [['arc_path', '電弧路徑', '滿電前最後 20 電壓出現純視覺電流軌跡。'], ['conductor_mark', '導體印記', '滿電雷擊命中者獲得 1 秒帶電標記，僅供辨識。']] },
  shamisen: { primary: [['staccato_solo', '破音獨奏', '撥弦・破音距離提高至 250px，傷害 15、暈眩 1 秒。'], ['canon_amplifier', '輪唱擴音', '輪唱殺陣第二波半徑提高至 400px；結束後敵人緩速 50% 3 秒。']], secondary: [['lingering_rhythm', '餘韻減速', '第四下普攻緩速持續提高至 1.2 秒。'], ['beat_echo', '節拍回響', '普攻成功造成傷害每 2 次 +1 跑速，最多 +7。']] },
  forgefire: { primary: [['flame_god_start', '炎神啟動', '炎神巨刃命中後，烈火旋斬冷卻歸零。'], ['king_of_flames', '烈火之王', '烈火旋斬可儲存 2 次；兩次施放間隔 1 秒。']], secondary: [['third_slash', '三斬', '火焰刀第三擊劍氣額外延伸改為 120px。'], ['burning_up', '燒起來', '跑速變為 28。']] }
};
